# Generated by Django 4.1.1 on 2022-09-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_comment_blog_commen_content_b11109_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Comentario'),
        ),
    ]
